apiVersion: v1
kind: Service
metadata:
  name: llmp-frontend-svc
  labels:
    app: llmp-frontent-app
spec:
  type: NodePort
  selector:
    app: llmp-frontent-app
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llmp-frontend-loadbalancer
spec:
  selector:
    app: llmp-frontent-app
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
